version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo `pwd`
      - echo ~
      - python3 -m venv ~/.venv
      - source ~/.venv/bin/activate
      - make install
  build:
    commands:
      - echo "post build commands"
